// Writes docs/voice-script.md: every line anybody says in the room, grouped
// by voice, with the id each recording should be named after.
//
//   npm run voices

import { writeFileSync } from 'node:fs';
import { allLines, SPEAKERS, type Line, type Speaker } from '../src/content/lines';
// importing the content registers its lines
import '../src/content/stations';
import '../src/content/phonebook';
import '../src/content/tv';
import '../src/content/calle';
import '../src/objects/house';

const ORDER: Speaker[] = [
  'mamaAndres',
  'andres',
  'mama',
  'abuelita',
  'papaAngie',
  'angie',
  'locutorRadioactiva',
  'cabinaRadioactiva',
  'tia',
  'equivocado',
  'negocio',
  'hora117',
  'locutorSuper',
  'locutorTropicana',
  'locutorRCN',
  'cunas',
  'tvNovela',
  'tvPresentador',
  'tvNarrador',
  'reciclador',
];

const byWho = new Map<Speaker, Line[]>();
for (const line of allLines()) {
  if (!byWho.has(line.who)) byWho.set(line.who, []);
  byWho.get(line.who)!.push(line);
}

let md = `# Voice recording script

Every line spoken in the room, grouped by voice. Every fixed line comes
included; live time announcements still use subtitles. A recording named after a
line's id adds or replaces its voice (the subtitle stays).

_Generated by \`npm run voices\` from the content files; don't edit by hand._

## How to record

- **Any phone works.** The phone line and the radio squeeze the sound
  through a narrow band anyway, so a voice memo in a quiet room is enough.
  Hold the phone about a hand's width from your mouth.
- **One file per line**, named with the line's id, e.g.
  \`llamada.andres.hola.m4a\`. Load them all at once in the backstage (the
  ⚙ in the corner, or the \` key): they are matched by name.
- **Or one take per voice**, reading the lines in order with two seconds of
  silence between them, and send the file over: it can be cut into lines.
- Say it like you would have said it in 1995, not like you're reading.
  Pauses, laughs, "eh..." are all welcome.

**Included cast:** all 186 fixed lines, covering the household, phone calls,
four radio stations, advertisements, and fictional TV programs. Your recordings
can replace individual takes. See \`src/assets/voices/README.md\` for the listening
checklist and generation program.

Lines that depend on the moment (the time on the radio and on 117) aren't
here; they stay as subtitles.

`;

let count = 0;
for (const who of ORDER) {
  const lines = byWho.get(who);
  if (!lines?.length) continue;
  const s = SPEAKERS[who];
  md += `## ${s.name}\n\n_${s.direction}_\n\n| id | line |\n|---|---|\n`;
  for (const line of lines) {
    md += `| \`${line.id}\` | ${line.text.replace(/\|/g, '\\|')} |\n`;
    count++;
  }
  md += '\n';
}
md = md.replace('Every line spoken in the room', `Every line spoken in the room (${count} lines)`);

writeFileSync(new URL('../docs/voice-script.md', import.meta.url), md);
console.log(`docs/voice-script.md: ${count} lines`);
